# Generated by Django 4.2.23 on 2025-08-28 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productexample',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productexample',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productexample',
            name='deletedat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productexample',
            name='updatedat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
